name: Sec

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.PASS }}" | docker login -u "${{ secrets.USER }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.USER }}/devsecops:2.0 .
        docker push ${{ secrets.USER }}/devsecops:2.0

  sast_test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit SAST scan
      run: bandit -r . -f json -o bandit-output.json || true  # Ignore failures to prevent pipeline from failing

    - name: Archive Bandit output
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: bandit_output
        path: bandit-output.json
