name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.PASS }}" | docker login -u "${{ secrets.USER }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.USER }}/devsecops:2.0 .
        docker push ${{ secrets.USER }}/devsecops:2.0
