name: Sec

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.PASS }}" | docker login -u "${{ secrets.USER }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.USER }}/devsecops:2.0 .
        docker push ${{ secrets.USER }}/devsecops:2.0

  owasp_test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub for pulling image
      run: echo "${{ secrets.PASS }}" | docker login -u "${{ secrets.USER }}" --password-stdin

    - name: Pull OWASP ZAP Docker image
      run: docker pull owasp/zap2docker-stable:latest

    - name: Run OWASP ZAP test
      run: |
        docker run -v $(pwd):/zap/wrk -u $(id -u ${USER}):$(id -g ${USER}) -t owasp/zap2docker-stable zap-baseline.py -t ${URL2} -J report_json

    - name: Archive OWASP ZAP report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: owasp_report
        path: report_json.json
